### PR TITLE
Bookstore: initialize project with components

### PR DESCRIPTION
**Pull request by Santosh-Konappanavar**
### In this milestone I,

- Setup the client-side routing using [React Router V6](https://reactrouter.com/en/main).
- Used React Router.
- Used React components.
- Deploy the gh-pages

### CODE REVIEW

**Comment by binhussen** [comment]
@Santosh-Konappanavar would you update the live demo link in your readme or replace it with coming soon ..text

**Comment by binhussen** [comment]
@Santosh-Konappanavar kindly, your live demo link is broken even after the update, please update it t proceed  the review

**Comment by Santosh-Konappanavar** [comment]
> @Santosh-Konappanavar kindly, your live demo link is broken even after the update, please update it t proceed the review

**Comment by Santosh-Konappanavar** [comment]
**@binhussen**  thanks for your feedback and I will update my deployment link upcoming project

**Comment by binhussen** [comment]
- @Santosh-Konappanavar Kindly, it is not necessary to deploy at this stage if you can't deploy it, however, broken link will lead bad experience so replace it with some text like `coming soon..` other wise it will be invalidated

**Review by binhussen — CHANGES_REQUESTED** [review]
Hi @Santosh-Konappanavar , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, the live demo link has been broken, Please fix the broken link or replace it with some text like `coming soon.. ` to have a better user experience :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Santosh-Konappanavar** [comment]
**@binhussen** thanks for your valuable time. It's updated now you can grow through it.

**Review by brytebee — APPROVED** [review]
Hi, @Santosh-Konappanavar 👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 



Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
